# Generated by Django 4.2.2 on 2023-07-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=20)),
                ('eml', models.EmailField(max_length=254)),
                ('num', models.CharField(max_length=20)),
                ('bd', models.CharField(max_length=20)),
                ('edct', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
