# Generated by Django 4.2.2 on 2023-08-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0004_companyprofile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='postjobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnm', models.CharField(max_length=20)),
                ('eml', models.EmailField(max_length=254)),
                ('ttl', models.CharField(max_length=20)),
                ('wktp', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('hybrid', 'hybrid')], max_length=20)),
                ('ex', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('>5', '>5')], max_length=20)),
                ('jbtp', models.CharField(choices=[('part time', 'part time'), ('Full time', 'Full time')], max_length=20)),
            ],
        ),
    ]
