# Generated by Django 4.2.2 on 2023-08-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0005_postjobmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postjobmodel',
            new_name='postjobmodel1',
        ),
    ]
