# Generated by Django 4.2.2 on 2023-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0007_applyjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='phno',
            field=models.CharField(max_length=20),
        ),
    ]
