# Generated by Django 4.2.2 on 2023-08-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0008_alter_applyjobmodel_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjobmodel',
            name='cv',
        ),
    ]
