# Generated by Django 4.2.2 on 2023-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0010_applyjobmodel1_delete_applyjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel1',
            name='cv',
            field=models.ImageField(upload_to='jobportalapp/static'),
        ),
    ]
